# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1486694384);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1486694504);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1486694624);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1486694264);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1486687748);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1486694144);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1486769219988");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1486771015988");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1486769221293");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1486772821293");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161216132416");
user_pref("browser.slowStartup.averageTime", 12064);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20161216132416");
user_pref("browser.startup.homepage_override.mstone", "45.6.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1483465236576");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1483378898247");
user_pref("datareporting.policy.firstRunTime", "1483378836576");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.firstPaint", 9623);
user_pref("datareporting.sessions.current.main", 2171);
user_pref("datareporting.sessions.current.sessionRestored", 12781);
user_pref("datareporting.sessions.current.startTime", "1486769192062");
user_pref("datareporting.sessions.current.totalTime", 37);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.5", "{\"s\":1486687499333,\"a\":18,\"t\":226,\"c\":false,\"m\":2422,\"fp\":14356,\"sr\":14601}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1486694017972,\"a\":129,\"t\":2213,\"c\":true,\"m\":1961,\"fp\":13703,\"sr\":15188}");
user_pref("datareporting.sessions.prunedIndex", 4);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.6.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1486694385);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.6.0");
user_pref("extensions.lastPlatformVersion", "45.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1481895435000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.6.0\",\"st\":1481895435000}}}");
user_pref("gecko.buildID", "20161216132416");
user_pref("gecko.mstone", "45.6.0");
user_pref("idle.lastDailyNotification", 1486687779);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1483378899);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20161216132416");
user_pref("media.gmp-manager.lastCheck", 1486687573);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1485033055);
user_pref("places.history.expiration.transient_current_max_pages", 48226);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1485033055);
user_pref("toolkit.startup.last_success", 1486769194);
user_pref("toolkit.telemetry.cachedClientID", "5d57b20f-c0b4-4484-9b10-d29430e1d913");
user_pref("toolkit.telemetry.previousBuildID", "20161216132416");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
